### ISSUE TITLE
when I Install Bluefog from Pip (GPU),some error happens

### ISSUE THREAD

**Issue by lkzs** [Bluefog-Lib/bluefog#107]
During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-install-teoqshks/bluefog_c270e8e510a24fe89dcf2ef326e7cd47/setup.py", line 585, in build_extensions
          build_torch_extension(self, options, torch_version)
        File "/tmp/pip-install-teoqshks/bluefog_c270e8e510a24fe89dcf2ef326e7cd47/setup.py", line 503, in build_torch_extension
          options['COMPILE_FLAGS'])
        File "/tmp/pip-install-teoqshks/bluefog_c270e8e510a24fe89dcf2ef326e7cd47/setup.py", line 266, in get_nccl_dirs
          'NCCL 2.4 library or its later version was not found (see error above).\n'
      distutils.errors.DistutilsPlatformError: NCCL 2.4 library or its later version was not found (see error above).
      Please specify correct NCCL location with the BLUEFOG_NCCL_HOME environment variable or combination of BLUEFOG_NCCL_INCLUDE and BLUEFOG_NCCL_LIB environment variables.
      
      BLUEFOG_NCCL_HOME - path where NCCL include and lib directories can be found
      BLUEFOG_NCCL_INCLUDE - path to NCCL include directory
      BLUEFOG_NCCL_LIB - path to NCCL lib directory
      
      error: Neither PyTorch or TensorFlow plugins were built. See errors above.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

?Encountered error while trying to install package.
\u2570\u2500> bluefog

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by hanbinhu** [comment]
Hi,

Thanks for trying out our package. It seems that it is related to NCCL installation. Please let us know what is installed NCCL version and the corresponding installation path. You can refer to [the official NCCL guide](https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html) for the installation. The suggested NCCL version should be above 2.7.

In addition, please let us know what are the steps you follow to install BlueFog. We recommend the steps in this [page](https://github.com/Bluefog-Lib/bluefog/wiki/BlueFog-Development-Guide#1-install-the-package-locally).

**Comment by lkzs** [comment]
The nccl version is 2.12 , because I don't have root,I install nccl by conda. I have tried install nccl by source code , but ' make -j12 src.build BUILDDIR=/home/chenz/software/nccl CUDA_HOME=/usr/local/cuda-10.2 NVCC_GENCODE="-gencode=arch=compute_35,code=sm_35"  ' command error

**Comment by ybc1991** [comment]
In this case, you have add `BLUEFOG_NCCL_HOME=<the path you installed>` before the `pip install` to tell BlueFog where to find the NCCL library. Please try it. If it still doesn't work, let's know

**Comment by lkzs** [comment]
I installed nccl by command 'conda install nccl' ,but don't have the nccl_include or nccl_lib file .Mabe this way is wrong. I don't have the root , how can I install nccl and bluefog?

**Comment by ybc1991** [comment]
Same comment in #108. Discussed offline, it is more likely the CUDA and NCCL installation issue instead of BlueFog's. Feel free to re-open if necessary.
