### ISSUE TITLE
NCCL issue with illegal memory access

### ISSUE THREAD

**Issue by hanbinhu** [Bluefog-Lib/bluefog#31]
Command to run: `bfrun -np 4 python examples/pytorch_benchmark.py --dist-optimizer=allreduce`
Commit aca0fec and after triggers nccl_controller.cc complaining `an illegal memory access was encountered` and other kinds of issues.

**Comment by ybc1991** [comment]
It is related to the NCCL version. However, not certain with the reason yet.

**Comment by Bluefog-Lib** [comment]
Maybe related to issue #44

**Comment by ybc1991** [comment]
It should be resolved completely
